# Generated by Django 5.2.1 on 2025-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('note_theorique', models.IntegerField(default=0)),
                ('note_pratique', models.IntegerField(default=0)),
                ('quiz_started', models.BooleanField(default=False)),
                ('cert_generated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
