# Generated by Django 5.2.1 on 2025-05-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_participant_a_participe_participant_reponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
